sudo: required

services:
  - docker

before_install:
  - docker build -t anchalgupta1996/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anchalgupta1996/react-test npm test

after_success:

  - docker build -t anchalgupta1996/multi-client ./client
  - docker build -t anchalgupta1996/multi-nginx ./nginx
  - docker build -t anchalgupta1996/multi-server ./server
  - docker build -t anchalgupta1996/multi-worker ./worker

  # Log In to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push anchalgupta1996/multi-client
  - docker push anchalgupta1996/multi-nginx
  - docker push anchalgupta1996/multi-server
  - docker push anchalgupta1996/multi-worker
